name: Update Repo

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
        
    - name: Set Repo Data
      run: |
        echo "REPO_NAME=$(basename ${{ github.repository }})" >> $GITHUB_ENV
        echo "REPO_NAME2=${GITHUB_REPOSITORY#*/}" >> $GITHUB_ENV
    - name: Get Repo Data
      run: |
        echo "${{ env.REPO_NAME2 }}"

    - name: Run the build script
      run: |
        php ./build/index.php ${{ env.REPO_NAME }}
        
    - name: Commit files
      run: |
        git config --local user.name ${{ github.actor }}
        git config --local user.email "${{ github.actor }}@users.noreply.github.com"
        git add .
        git commit -m "generated static version"
        
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        force: true
